version: "3.7"
services:
    # imagem do projeto Teste/Pontue
    movie_app:
        container_name: movie_web
        build:
            args:
                user: euclides
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel:10
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - net-movie

    # nginx
    nginx:
        container_name: movie_nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8180:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - net-movie

    # db mysql
    mysql:
        container_name: movie_db
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_USER: '${DB_USERNAME}'
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - net-movie
    phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
            - 8081:80
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        links:
            - "mysql:db"
        depends_on:
            - mysql
        networks:
            - net-movie

networks:
    net-movie:
        driver: bridge
